services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: hospital-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hospital
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - hospital-network

  # Spring Boot Application
  app:
    build: .
    container_name: hospital-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: hospital
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - hospital-network
    restart: unless-stopped
    volumes:
      - ./src/main/frontend:/app/src/main/frontend

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: hospital-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - hospital-network
    restart: unless-stopped

  frontend-watch:
    image: node:18
    working_dir: /app
    volumes:
      - ./src/main/frontend:/app
      - ./src/main/resources/static:/app/../resources/static
    command: npm run watch -- -o ../resources/static/main.css

volumes:
  mysql_data:

networks:
  hospital-network:
    driver: bridge
