INSERT INTO doctor_schedule(hospital, name, day, time, specialization) VALUES
('Rumah Sakit Buah Hati Pamulang', 'dr. Irwan Eka Putra, Sp.OG', 'Senin', '14:00-17:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Irwan Eka Putra, Sp.OG', 'Minggu', '09:00-12:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Medissa Diantika, Sp.OG', 'Selasa', '14:00-16:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Medissa Diantika, Sp.OG', 'Jumat', '13:00-15:30', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. E. Rohati, Sp.OG', 'Senin', '09:00-13:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. E. Rohati, Sp.OG', 'Selasa', '09:00-13:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. E. Rohati, Sp.OG', 'Kamis', '15:00-18:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. E. Rohati, Sp.OG', 'Jumat', '16:00-18:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. E. Rohati, Sp.OG', 'Sabtu', '09:00-13:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ismail Yahya, Sp.OG', 'Senin', '19:30-21:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ismail Yahya, Sp.OG', 'Selasa', '18:00-Selesai', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ismail Yahya, Sp.OG', 'Rabu', '13:00-17:30', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ismail Yahya, Sp.OG', 'Kamis', '10:00-13:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ismail Yahya, Sp.OG', 'Jumat', '09:00-13:00', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ismail Yahya, Sp.OG', 'Jumat', '18:00-Selesai', 'Spesialis Kebidanan & Kandungan'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ismail Yahya, Sp.OG', 'Sabtu', '18:00-Selesai', 'Spesialis Kebidanan & Kandungan'),

('Rumah Sakit Buah Hati Pamulang', 'dr. Aditya Suryansyah, Sp.A (K)', 'Senin', '19:00-21:00', 'Subspesialis Endokrinologi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Aditya Suryansyah, Sp.A (K)', 'Rabu', '19:00-21:00', 'Subspesialis Endokrinologi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Aditya Suryansyah, Sp.A (K)', 'Jumat', '16:30-19:00', 'Subspesialis Endokrinologi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Aditya Suryansyah, Sp.A (K)', 'Sabtu', '09:00-13:00', 'Subspesialis Endokrinologi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ellya Marliah, Sp.A', 'Senin', '09:00-12:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ellya Marliah, Sp.A', 'Selasa', '09:00-12:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ellya Marliah, Sp.A', 'Rabu', '09:00-12:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ellya Marliah, Sp.A', 'Kamis', '09:00-12:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ellya Marliah, Sp.A', 'Jumat', '09:00-12:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Endang Triningsih, Sp.A (K)', 'Selasa', '09:00-10:30', 'Subspesialis Endokrinologi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Endang Triningsih, Sp.A (K)', 'Rabu', '17:00-19:00', 'Subspesialis Endokrinologi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Endang Triningsih, Sp.A (K)', 'Kamis', '09:00-10:30', 'Subspesialis Endokrinologi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Endang Triningsih, Sp.A (K)', 'Jumat', '09:00-10:30', 'Subspesialis Endokrinologi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Fajar Subroto, Sp.A (K)', 'Senin', '17:00-19:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Fajar Subroto, Sp.A (K)', 'Selasa', '18:30-21:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Fajar Subroto, Sp.A (K)', 'Kamis', '18:30-21:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Fajar Subroto, Sp.A (K)', 'Jumat', '20:00-22:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Fajar Subroto, Sp.A (K)', 'Sabtu', '18:30-21:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Firmansyah Chatab, Sp.A', 'Senin', '09:00-11:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Firmansyah Chatab, Sp.A', 'Selasa', '20:00-Selesai', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Firmansyah Chatab, Sp.A', 'Rabu', '09:00-11:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Firmansyah Chatab, Sp.A', 'Kamis', '20:00-Selesai', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Firmansyah Chatab, Sp.A', 'Jumat', '20:00-Selesai', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, Sp.A', 'Senin', '12:00-19:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, Sp.A', 'Selasa', '12:00-19:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, Sp.A', 'Rabu', '12:00-19:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, Sp.A', 'Kamis', '12:00-19:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, Sp.A', 'Jumat', '12:00-19:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, Sp.A', 'Sabtu', '12:00-16:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, Sp.A', 'Minggu', '10:00-13:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Labiqotullababah Ahasmi, Sp.A', 'Selasa', '11:00-15:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Labiqotullababah Ahasmi, Sp.A', 'Rabu', '12:00-14:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Labiqotullababah Ahasmi, Sp.A', 'Kamis', '11:00-15:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Labiqotullababah Ahasmi, Sp.A', 'Sabtu', '09:00-12:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Fitriyani, Sp.A', 'Senin', '11:00-14:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Fitriyani, Sp.A', 'Selasa', '18:30-20:30', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Fitriyani, Sp.A', 'Kamis', '18:30-20:30', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Fitriyani, Sp.A', 'Sabtu', '10:00-13:00', 'Spesialis Anak'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Fitriyani, Sp.A', 'Minggu', '08:00-10:00', 'Spesialis Anak'),

('Rumah Sakit Buah Hati Pamulang', 'dr. Sandhi Ari Susanti Sp.THT-KL', 'Senin', '13.00 - 15.00', 'Spesialis THT'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Sandhi Ari Susanti Sp.THT-KL', 'Kamis', '15.00 - 17.00', 'Spesialis THT'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Sandhi Ari Susanti Sp.THT-KL', 'Sabtu', '12.00 - 15.00', 'Spesialis THT'),

('Rumah Sakit Buah Hati Pamulang', 'dr. M. Reza Jauhari Zen, Sp.B', 'Rabu', '14.00 - 17.00', 'Spesialis Bedah'),
('Rumah Sakit Buah Hati Pamulang', 'dr. R. Diky Laksmana, Sp.B,FICS ', 'Senin', '12.00 - 14.00', 'Spesialis Bedah'),
('Rumah Sakit Buah Hati Pamulang', 'dr. R. Diky Laksmana, Sp.B,FICS ', 'Selasa', '19.00 - 21.00', 'Spesialis Bedah'),
('Rumah Sakit Buah Hati Pamulang', 'dr. R. Diky Laksmana, Sp.B,FICS ', 'Rabu', '12.00 - 14.00', 'Spesialis Bedah'),
('Rumah Sakit Buah Hati Pamulang', 'dr. R. Diky Laksmana, Sp.B,FICS ', 'Kamis', '19.00 - 21.00', 'Spesialis Bedah'),
('Rumah Sakit Buah Hati Pamulang', 'dr. R. Diky Laksmana, Sp.B,FICS ', 'Jumat', '19.00 - 21.00', 'Spesialis Bedah'),

('Rumah Sakit Buah Hati Pamulang', 'drg. Bono Widiastuti, Sp. KGA', 'Rabu', '17:00-20:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Bono Widiastuti, Sp. KGA', 'Jumat', '17:00-20:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Rini Triani, Sp. KGA', 'Selasa', '17:00-20:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Rini Triani, Sp. KGA', 'Kamis', '17:00-20:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Murni', 'Senin', '16:00-19:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Murni', 'Sabtu', '13:00-16:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Nastiti Rahajeng', 'Selasa', '09:00-12:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Nastiti Rahajeng', 'Jumat', '09:00-12:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Riani Apsari', 'Rabu', '09:00-12:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Riani Apsari', 'Jumat', '17:00-20:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Cicilia Triana', 'Senin', '09:00-12:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Cicilia Triana', 'Kamis', '09:00-12:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Cicilia Triana', 'Jumat', '09:00-12:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Syleovina Rizkita Sari', 'Rabu', '13:00-16:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Syleovina Rizkita Sari', 'Kamis', '13:00-16:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Laksmi Kusumaningtyas', 'Selasa', '13:00-16:00', 'Dokter Gigi'),
('Rumah Sakit Buah Hati Pamulang', 'drg. Laksmi Kusumaningtyas', 'Minggu', '09:00-12:00', 'Dokter Gigi'),

('Rumah Sakit Buah Hati Pamulang', 'dr. Sekar Asmara Jayaning Diah', 'Senin', '08:00-12:00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Sekar Asmara Jayaning Diah', 'Selasa', '08:00-12:00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Sekar Asmara Jayaning Diah', 'Rabu', '08:00-12:00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Sekar Asmara Jayaning Diah', 'Kamis', '08:00-12:00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Sekar Asmara Jayaning Diah', 'Jumat', '08:00-12:00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ning Indah Permatasari', 'Senin', '12.00-16.00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ning Indah Permatasari', 'Selasa', '12.00-16.00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ning Indah Permatasari', 'Rabu', '12.00-16.00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ning Indah Permatasari', 'Kamis', '12.00-16.00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ning Indah Permatasari', 'Jumat', '12.00-16.00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Amalina Fitrasari', 'Selasa', '18.00-20.00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Amalina Fitrasari', 'Rabu', '18.00-20.00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Amalina Fitrasari', 'Kamis', '18.00-20.00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Reza Hafiyyan', 'Sabtu', '08.00-16.00', 'Dokter Umum'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Reza Hafiyyan', 'Minggu', '08.00-16.00', 'Dokter Umum'),

('Rumah Sakit Buah Hati Pamulang', 'dr. Shella Riana ', 'Selasa', '09.00-12.00', 'Poli Laktasi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Shella Riana ', 'Kamis', '09.00-12.00', 'Poli Laktasi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Shella Riana ', 'Sabtu', '09.00-12.00', 'Poli Laktasi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Sarah Kamilah', 'Senin', '09.00-12.00', 'Poli Laktasi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Sarah Kamilah', 'Rabu', '09.00-12.00', 'Poli Laktasi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, SpA ', 'Senin', '12.00-19.00', 'Poli Laktasi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, SpA ', 'Selasa', '16.00-19.00', 'Poli Laktasi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, SpA ', 'Rabu', '12.00-19.00', 'Poli Laktasi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, SpA ', 'Kamis', '16.00-19.00', 'Poli Laktasi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, SpA ', 'Jumat', '12.00-19.00', 'Poli Laktasi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hetty Wati Napitupulu, SpA ', 'Sabtu', '12.00-16.00', 'Poli Laktasi'),

('Rumah Sakit Buah Hati Pamulang', 'dr. Sri Dewi Imayanti, Sp.Rad ', 'Sabtu', '08.00-10.00', 'Radiologi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Sri Dewi Imayanti, Sp.Rad ', 'Sabtu', '08.00-10.00', 'Radiologi'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Sri Dewi Imayanti, Sp.Rad ', 'Sabtu', '08.00-10.00', 'Radiologi'),

('Rumah Sakit Buah Hati Pamulang', 'dr. Ryandri Yovanda, Sp.PD', 'Senin', '09.00-11.00', 'Spesialis Penyakit Dalam'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ryandri Yovanda, Sp.PD', 'Selasa', '19.00-21.00', 'Spesialis Penyakit Dalam'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ryandri Yovanda, Sp.PD', 'Kamis', '09.00-11.00', 'Spesialis Penyakit Dalam'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ryandri Yovanda, Sp.PD', 'Jumat', '15.00-17.00', 'Spesialis Penyakit Dalam'),

('Rumah Sakit Buah Hati Pamulang', 'dr. Radia Puri', 'Setiap Hari', '24 Jam', 'Dokter IGD'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Nabila Maudy Salma', 'Setiap Hari', '24 Jam', 'Dokter IGD'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Amalina Fitrasari', 'Setiap Hari', '24 Jam', 'Dokter IGD'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Taqiyya Maryam', 'Setiap Hari', '24 Jam', 'Dokter IGD'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Ning Indah Permatasari', 'Setiap Hari', '24 Jam', 'Dokter IGD'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Saflan Ady Saputra', 'Setiap Hari', '24 Jam', 'Dokter IGD'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Reza Hafiyyan', 'Setiap Hari', '24 Jam', 'Dokter IGD'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Khusnul Khotimah', 'Setiap Hari', '24 Jam', 'Dokter IGD'),

('Rumah Sakit Buah Hati Pamulang', 'dr. Hikmah Amayanti Adil, Sp.KFR', 'Rabu', '15:00-17:00', 'Spesialis Rehabilitasi Medik'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hikmah Amayanti Adil, Sp.KFR', 'Jumat', '09:00-12:00', 'Spesialis Rehabilitasi Medik'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Hikmah Amayanti Adil, Sp.KFR', 'Sabtu', '15:00-17:00', 'Spesialis Rehabilitasi Medik');

('Rumah Sakit Buah Hati Pamulang', 'dr. Rika Ilham Munazat, Sp.An', 'Senin', '16:00-17:00', 'Poliklinik Nyeri'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Rika Ilham Munazat, Sp.An', 'Rabu', '16:00-17:00', 'Poliklinik Nyeri'),
('Rumah Sakit Buah Hati Pamulang', 'dr. Rika Ilham Munazat, Sp.An', 'Jumat', '16:00-17:00', 'Poliklinik Nyeri'),

('Rumah Sakit Buah Hati Pamulang', 'Susilawaty, SST.Ft', 'Senin', '10:00-17:00', 'Tumbuh Kembang'),
('Rumah Sakit Buah Hati Pamulang', 'Susilawaty, SST.Ft', 'Selasa', '10:00-17:00', 'Tumbuh Kembang'),
('Rumah Sakit Buah Hati Pamulang', 'Susilawaty, SST.Ft', 'Rabu', '10:00-17:00', 'Tumbuh Kembang'),
('Rumah Sakit Buah Hati Pamulang', 'Susilawaty, SST.Ft', 'Kamis', '10:00-17:00', 'Tumbuh Kembang'),
('Rumah Sakit Buah Hati Pamulang', 'Susilawaty, SST.Ft', 'Jumat', '10:00-17:00', 'Tumbuh Kembang'),
('Rumah Sakit Buah Hati Pamulang', 'Susilawaty, SST.Ft', 'Sabtu', '10:00-17:00', 'Tumbuh Kembang');

-- Insert basic doctor data from schedule data
INSERT INTO doctor (name, specialization)
SELECT DISTINCT name, specialization FROM doctor_schedule;
