/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "../resources/templates/**/*.html", // Spring Boot Thymeleaf templates
    "../resources/static/js/**/*.js", // JavaScript files in static folder
    "./main.css", // Main CSS file
  ],
  theme: {
    extend: {
      colors: {
        primary: "#E6521F",
        secondary: "#FB9E3A",
        accent: "#17695B",
      },
      animation: {
        "fade-in": "fadeIn 0.3s ease-out",
        float: "float 3s ease-in-out infinite",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
    },
  },
  plugins: [require("daisyui"), require("flowbite/plugin")],
  // Safelist untuk class yang tidak terdeteksi otomatis
  safelist: [
    // Dynamic classes yang sering digunakan
    "hidden",
    "block",
    "flex",
    "lg:block",
    "lg:hidden",
    "sm:block",
    "sm:hidden",
    // Modal classes
    "modal-open",
    "animate-fadeIn",
    "animate-scaleIn",
    "animate-slideIn",
    // Modal specific classes
    "fixed",
    "inset-0",
    "bg-black/60",
    "backdrop-blur-sm",
    "z-[9999]",
    "items-center",
    "justify-center",
    "p-4",
    "bg-white/95",
    "backdrop-blur-xl",
    "rounded-3xl",
    "shadow-2xl",
    "w-full",
    "max-w-lg",
    "mx-auto",
    "relative",
    "transform",
    "border",
    "border-white/30",
    // Pagination classes
    "pagination-controls",
    "pagination-info",
    "pagination-buttons",
    "pagination-prev",
    "pagination-next",
    "pagination-page",
    "pagination-active",
    "pagination-disabled",
    // Essential utility classes
    "text-center",
    "text-left",
    "text-right",
    "font-bold",
    "font-semibold",
    "text-sm",
    "text-base",
    "text-lg",
    "text-xl",
    "text-2xl",
    "text-3xl",
    // Essential spacing
    "p-4",
    "p-6",
    "p-8",
    "px-4",
    "px-6",
    "px-8",
    "py-4",
    "py-6",
    "py-8",
    "m-4",
    "m-6",
    "m-8",
    "mx-4",
    "mx-6",
    "mx-8",
    "my-4",
    "my-6",
    "my-8",
    // Essential responsive
    "sm:block",
    "sm:hidden",
    "sm:text-lg",
    "sm:p-6",
    "md:flex",
    "md:hidden",
    "md:text-xl",
    "md:p-8",
    "lg:block",
    "lg:hidden",
    "lg:text-2xl",
    "lg:p-12",
    // Button classes
    "btn",
    "btn-primary",
    "btn-secondary",
    "bg-primary",
    "bg-secondary",
    "text-white",
    "hover:bg-primary",
    "hover:bg-secondary",
    // Form classes
    "form-control",
    "input",
    "select",
    "textarea",
    // Table classes
    "table",
    "table-auto",
    "table-fixed",
    "thead",
    "tbody",
    "tr",
    "th",
    "td",
    // Card classes
    "card",
    "card-body",
    "card-title",
    "card-text",
  ],
};
